@startuml
skinparam {
    dpi 200
    shadowing false
    arrowFontSize 12
    defaultFontSize 12
    defaultTextAlignment center
    arrowThickness 1
    arrowColor black
    arrowFontColor black
    maxMessageSize 100
    wrapWidth 200
    nodeSpacing 50
    rankSpacing 50
    direction left to right
}

title Main Loop

start
repeat
: Read can messages;
: Update the LEDS;
if (AMS error state OR AIR close) then (yes)
    :Display alert;
endif

: Update the Display;

repeat while (true)
stop
@enduml
